name: Main Branch Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  md-to-pdf-and-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install md2pdf

      - name: Convert all md to pdf
        run: |
          for file in $(find . -type f -name "*.md"); do
            md2pdf "$file" --output "${file%.md}.pdf"
          done

      - name: Commit and push PDFs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.pdf
          git commit -m "Add/update PDF files from Markdown" || echo "No changes to commit"
          git push

      - name: Send preview links to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPO: ${{ github.repository }}
        run: |
          BRANCH=main
          MSG="PDF Previews:\n"
          for pdf in $(find . -type f -name "*.pdf"); do
            # Remove leading ./ from path
            pdf_path="${pdf#./}"
            # Construct raw.githubusercontent.com link
            url="https://github.com/${REPO}/blob/${BRANCH}/${pdf_path}?raw=true"
            MSG="${MSG}${pdf_path}: ${url}\n"
          done
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            --data-urlencode "text=${MSG}"
