name: Main Branch Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  md-to-pdf-and-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install latest md-to-pdf
        run: npm install -g md-to-pdf@latest

      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libxss1 \
            libasound2t64 \
            libgbm1

      - name: Convert all md to pdf (GitHub style)
        env:
          PUPPETEER_ARGS: "--no-sandbox"
        run: |
          for file in $(find . -type f -name "*.md"); do
            echo "md-to-pdf \"$file\" --stylesheet github-markdown-css \"${file%.md}.pdf\""
            md-to-pdf "$file" --stylesheet github-markdown-css "${file%.md}.pdf"
          done

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.x"

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install mdpdf

      # - name: Convert all md to pdf
      #   run: |
      #     for file in $(find . -type f -name "*.md"); do
      #       echo "md2pdf "$file" --output "${file%.md}.pdf""
      #       mdpdf "$file" --output "${file%.md}.pdf"
      #     done

      - name: Commit and push PDFs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.pdf
          git commit -m "Add/update PDF files from Markdown" || echo "No changes to commit"
          git push

      - name: Generate PDF URLs
        id: pdf_urls
        run: |
          urls=""
          for file in $(find . -type f -name "*.pdf"); do
            # Remove leading ./ from path
            clean_file="${file#./}"
            url="https://github.com/${{ github.repository }}/raw/main/${clean_file}\n"
            urls="${urls}${url}\n"
          done
          echo -e "urls<<EOF\n${urls}EOF" >> $GITHUB_OUTPUT

      - name: Send PDF URLs via Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Your PDF(s) are ready:

            Repository: ${{ github.repository }}

            ${{ steps.pdf_urls.outputs.urls }}
