name: Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  md-to-pdf-and-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypandoc

      - name: Find changed md files
        id: changed-md
        run: |
          git fetch origin main
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || true
        continue-on-error: true

      - name: Convert md to pdf using Python
        if: steps.changed-md.outputs.files != ''
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$'); do
            python -c "import pypandoc; pypandoc.convert_file('$file', 'pdf', outputfile='${file%.md}.pdf')"
          done

      - name: Send PDFs to Telegram
        if: steps.changed-md.outputs.files != ''
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$'); do
            pdf="${file%.md}.pdf"
            if [ -f "$pdf" ]; then
              curl -s -F document=@"$pdf" "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument?chat_id=${TELEGRAM_CHAT_ID}"
            fi
          done
