name: Main Branch Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  md-to-pdf-and-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mdpdf

      - name: Convert all md to pdf
        run: |
          for file in $(find . -type f -name "*.md"); do
            echo "md2pdf "$file" --output "${file%.md}.pdf""
            mdpdf "$file" --output "${file%.md}.pdf"
          done

      - name: Commit and push PDFs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.pdf
          git commit -m "Add/update PDF files from Markdown" || echo "No changes to commit"
          git push

      - name: Send notification to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          PDF_FILES=$(find . -type f -name "*.pdf" | sed 's|^\./||')
          MSG="Your PDF(s) are ready:\n"
          for pdf in $PDF_FILES; do
          MSG="${MSG}${REPO_URL}/blob/main/${pdf}\n"
          done
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          --data-urlencode "text=${MSG}"
